module "acr" {
  source              = "./modules/acr"
  resource_group_name = var.resource_group_name
  location            = var.location
  name                = var.acr_name
  sku                 = var.acr_sku
}

module "postgres" {
  source              = "./modules/postgres-flexible"
  resource_group_name = var.resource_group_name
  location            = coalesce(var.pg_location, var.location)
  name                = var.pg_name
  pg_version          = var.pg_version
  sku                 = var.pg_sku
  storage_mb          = var.pg_storage_mb
  # no need to supply login and password, will be auto generated by the module
}
