variable "release_name" {
  description = "The name of the Helm release."
  type        = string
  default     = "monitoring"
}

variable "namespace" {
  description = "The Kubernetes namespace for Prometheus. Will be created if it does not exist."
  type        = string
  default     = "monitoring"
}

variable "chart_version" {
  description = "The version of the Helm chart to deploy."
  type        = string
  default     = "80.13.2"
}

variable "retention" {
  description = "Prometheus data retention period (e.g. 15d, 7d)."
  type        = string
  default     = "15d"
}

variable "admin_password" {
  description = "Grafana admin password. If empty, a random password will be generated by the module."
  type        = string
  default     = ""
}

variable "requests_memory" {
  description = "Memory request for Prometheus components (e.g. 512Mi)."
  type        = string
  default     = "512Mi"
}

variable "requests_cpu" {
  description = "CPU request for Prometheus components (e.g. 200m)."
  type        = string
  default     = "200m"
}

variable "limits_memory" {
  description = "Memory limit for Prometheus components (e.g. 1Gi)."
  type        = string
  default     = "1Gi"
}

variable "limits_cpu" {
  description = "CPU limit for Prometheus components (e.g. 500m)."
  type        = string
  default     = "500m"
}

variable "grafana_path" {
  description = "The path prefix for accessing Grafana (e.g. /grafana)."
  type        = string
  default     = "/grafana"
}

variable "grafana_ingress" {
  description = "Ingress configuration for Grafana."
  type = object({
    host       = string
    class_name = string
  })
  default = null
}

variable "service_monitor" {
  description = "Configuration for additional ServiceMonitor to monitor all services in specified namespaces."
  type = object({
    namespaces   = list(string)
    port         = string
    metrics_path = string
    interval     = string
  })
  default = null
}

variable "grafana_additional_data_sources" {
  description = "Additional Grafana data sources to configure."
  type        = list(object({
    name       = string
    type       = string
    url        = string
    access     = optional(string, "proxy")
    is_default = optional(bool, false)
    json_data  = optional(map(any), {})
  }))
  default = []
}
